### ISSUE TITLE
Kodi 17.4

### ISSUE THREAD

**Issue by oslyak** [mintsoft/kodi.plugin.video.pluralsight#14]
```
00:00:59.410 T:140549654264128   DEBUG: ------ Window Init (DialogBusy.xml) ------
00:00:59.880 T:140547058542336  NOTICE: PluralSight Duration@PostKodiInit : 0.000104904174805
00:00:59.880 T:140547058542336  NOTICE: PluralSight Duration@PostSettingsLoad : 0.000240802764893
00:00:59.880 T:140547058542336  NOTICE: PluralSight Duration@pre-cache check : 0.000262022018433
00:00:59.886 T:140547058542336  NOTICE: PluralSight Duration@pre-API-get : 0.0059289932251
00:01:01.094 T:140548086306560   DEBUG: Version Check: Version installed {u'major': 17, u'tag': u'stable', u'minor': 4, u'revision': u'20170822-nogitfound'}
00:01:01.094 T:140548086306560   DEBUG: Version Check: Version available  {u'major': u'17', u'extrainfo': u'final', u'tagversion': u'', u'tag': u'stable', u'addon_support': u'yes', u'minor': u'4', u'revision': u'20170822-7fc6da0'}
00:01:01.094 T:140548086306560   DEBUG: Version Check: There is no newer stable available
00:01:01.094 T:140548086306560    INFO: CPythonInvoker(0, /home/anton/.kodi/addons/service.xbmc.versioncheck/service.py): script successfully run
00:01:01.107 T:140548086306560    INFO: Python script stopped
00:01:01.107 T:140548086306560   DEBUG: Thread LanguageInvoker 140548086306560 terminating
00:01:01.574 T:140547058542336  NOTICE: PluralSight Duration@post-API-get : 1.69362998009
00:01:01.574 T:140547058542336  NOTICE: PluralSight Duration@Re-priming DB from the API response (slow-path) : 1.69368600845
00:01:01.576 T:140547058542336   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'simplejson.scanner.JSONDecodeError'>
                                            Error Contents: Expecting value: line 3 column 1 (char 2)
                                            Traceback (most recent call last):
                                              File "/home/anton/.kodi/addons/plugin.video.pluralsight/addon.py", line 396, in <module>
                                                main()
                                              File "/home/anton/.kodi/addons/plugin.video.pluralsight/addon.py", line 349, in main
                                                catalogue.update(r.headers["ETag"], r.json())
                                              File "/home/anton/.kodi/addons/plugin.video.pluralsight/resources/lib/requests/models.py", line 866, in json
                                                return complexjson.loads(self.text, **kwargs)
                                              File "/usr/lib/python2.7/dist-packages/simplejson/__init__.py", line 516, in loads
                                                return _default_decoder.decode(s)
                                              File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 374, in decode
                                                obj, end = self.raw_decode(s)
                                              File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 404, in raw_decode
                                                return self.scan_once(s, idx=_w(s, idx).end())
                                            JSONDecodeError: Expecting value: line 3 column 1 (char 2)
                                            -->End of Python script error report<--

```

**Comment by frankhommers** [comment]
Same problem on Kodi 17.5rc1 (LibreElec)
```text22:41:25.835 T:3595559840  NOTICE: PluralSight Duration@PostKodiInit : 0.000412940979004
22:41:25.836 T:3595559840  NOTICE: PluralSight Duration@PostSettingsLoad : 0.00196886062622
22:41:25.836 T:3595559840  NOTICE: PluralSight Duration@pre-cache check : 0.00212383270264
22:41:25.839 T:3595559840  NOTICE: PluralSight Duration@pre-API-get : 0.00494384765625
22:41:26.790 T:3595559840  NOTICE: PluralSight Duration@post-API-get : 0.953071832657
22:41:26.791 T:3595559840  NOTICE: PluralSight Duration@Re-priming DB from the API response (slow-path) : 0.956068992615
22:41:26.799 T:3595559840   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'simplejson.scanner.JSONDecodeError'>
                                            Error Contents: Expecting value: line 3 column 1 (char 2)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.pluralsight/addon.py", line 396, in <module>
                                                main()
                                              File "/storage/.kodi/addons/plugin.video.pluralsight/addon.py", line 349, in main
                                                catalogue.update(r.headers["ETag"], r.json())
                                              File "/storage/.kodi/addons/plugin.video.pluralsight/resources/lib/requests/models.py", line 866, in json
                                                return complexjson.loads(self.text, **kwargs)
                                              File "/usr/lib/python2.7/site-packages/simplejson/__init__.py", line 516, in loads
                                              File "/usr/lib/python2.7/site-packages/simplejson/decoder.py", line 370, in decode
                                              File "/usr/lib/python2.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
                                              File "/usr/lib/python2.7/site-packages/simplejson/scanner.py", line 127, in scan_once
                                              File "/usr/lib/python2.7/site-packages/simplejson/scanner.py", line 118, in _scan_once
                                            JSONDecodeError: Expecting value: line 3 column 1 (char 2)
                                            -->End of Python script error report<--
22:41:26.971 T:4099749984   ERROR: GetDirectory - Error getting plugin://plugin.video.pluralsight/
22:41:26.972 T:4099749984   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.pluralsight/) failed`

**Comment by BigYellowHammer** [comment]
Looks like pluralsight changed their urls.
https://www.pluralsight.com/metadata/live/courses/ no longer exists.
I found https://app.pluralsight.com/search/proxy?i=1&q1=course&x1=categories&m_Sort=updated_date but havent tried if it works.
@mintsoft can you send example response that catalogue.update() was accepting?

**Comment by mintsoft** [comment]
@BigYellowHammer It was a giant (>20MB) JSON object with all course information on it; I don't have a copy of it banging around unfortunately. Judging by the output of the search API you've found, the entire addon will need rewriting to remove the menu based on categories.
