### ISSUE TITLE
Handling of incorrect username and password is TERRIBLE

### ISSUE THREAD

**Issue by mintsoft** [mintsoft/kodi.plugin.video.pluralsight#4]
I'm not sure if this is because I have not trashed the DB or what yet, however this is in the `kodi.log`:

```
15:01:55 T:2518678336   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'simplejson.scanner.JSONDecodeError'>
                                            Error Contents: Expecting value: line 1 column 1 (char 0)
                                            Traceback (most recent call last):
                                              File "/home/rob/.kodi/addons/plugin.video.pluralsight/addon.py", line 396, in <module>
                                                main()
                                              File "/home/rob/.kodi/addons/plugin.video.pluralsight/addon.py", line 389, in main
                                                recent_view(catalogue)
                                              File "/home/rob/.kodi/addons/plugin.video.pluralsight/addon.py", line 216, in recent_view
                                                token = login(catalogue)
                                              File "/home/rob/.kodi/addons/plugin.video.pluralsight/addon.py", line 77, in login
                                                login_token = response.json()["Token"]
                                              File "/home/rob/.kodi/addons/plugin.video.pluralsight/resources/lib/requests/models.py", line 819, in json
                                                return json.loads(self.text, **kwargs)
                                              File "/usr/lib/python2.7/dist-packages/simplejson/__init__.py", line 488, in loads
                                                return _default_decoder.decode(s)
                                              File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 370, in decode
                                                obj, end = self.raw_decode(s)
                                              File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 389, in raw_decode
                                                return self.scan_once(s, idx=_w(s, idx).end())
                                            JSONDecodeError: Expecting value: line 1 column 1 (char 0)
                                            -->End of Python script error report<--
```

If the schema needs migrating then we could probably do with implementing something to make the upgrade to 1.1.0 stable for our users

**Comment by mintsoft** [comment]
The same is true of bookmarks:

```
15:09:00 T:2432777024  NOTICE: PluralSight Duration@PostKodiInit : 0.0010621547699
15:09:00 T:2432777024  NOTICE: PluralSight Duration@PostSettingsLoad : 0.00281500816345
15:09:00 T:2432777024  NOTICE: PluralSight Duration@pre-cache check : 0.00312399864197
15:09:00 T:2432777024  NOTICE: PluralSight Duration@catalogue-loaded : 0.00391912460327
15:09:00 T:2432777024  NOTICE: PluralSight Duration@Getting bookmarked courses: https://app.pluralsight.com/data/bookmarks : 0.00419902801514
15:09:00 T:2432777024  NOTICE: PluralSight Duration@Starting login : 0.00437498092651
15:09:00 T:2432777024  NOTICE: PluralSight Duration@Using url: https://www.pluralsight.com/metadata/live/users/dee-veloper/login : 0.00459814071655
15:09:01 T:2432777024  NOTICE: PluralSight Duration@Completed login, Response Code:403 : 1.14208602905
15:09:01 T:2432777024   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: 'NoneType' object is not callable
                                            Traceback (most recent call last):
                                              File "/home/rob/.kodi/addons/plugin.video.pluralsight/addon.py", line 396, in <module>
                                                main()
                                              File "/home/rob/.kodi/addons/plugin.video.pluralsight/addon.py", line 387, in main
                                                bookmarks_view(catalogue)
                                              File "/home/rob/.kodi/addons/plugin.video.pluralsight/addon.py", line 200, in bookmarks_view
                                                token = login(catalogue)
                                              File "/home/rob/.kodi/addons/plugin.video.pluralsight/addon.py", line 77, in login
                                                login_token = response.json()["Token"]
                                              File "/home/rob/.kodi/addons/plugin.video.pluralsight/resources/lib/requests/models.py", line 819, in json
                                                return json.loads(self.text, **kwargs)
                                              File "/usr/lib/python2.7/dist-packages/simplejson/__init__.py", line 488, in loads
                                                return _default_decoder.decode(s)
                                              File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 370, in decode
                                                obj, end = self.raw_decode(s)
                                              File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 389, in raw_decode
                                                return self.scan_once(s, idx=_w(s, idx).end())
                                              File "/usr/lib/python2.7/dist-packages/simplejson/scanner.py", line 33, in __init__
                                                ValueError.__init__(self, errmsg(msg, doc, pos, end=end))
                                            TypeError: 'NoneType' object is not callable
                                            -->End of Python script error report<--
15:09:01 T:3002636096   ERROR: GetDirectory - Error getting plugin://plugin.video.pluralsight/?cached=true&mode=bookmarks
15:09:01 T:3002636096   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.pluralsight/?cached=true&mode=bookmarks) failed
```

**Comment by mintsoft** [comment]
¬_¬ I think it's because the username & password has been changed as you said @supertom44 We should definitely make the errors better here if it is.

**Comment by mintsoft** [comment]
When attempting to play a video:

```
15:12:42 T:2415643456   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
 - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <type 'exceptions.TypeError'>
Error Contents: 'NoneType' object is not callable
Traceback (most recent call last):
  File "/home/rob/.kodi/addons/plugin.video.pluralsight/addon.py", line 396, in <module>
    main()
  File "/home/rob/.kodi/addons/plugin.video.pluralsight/addon.py", line 385, in main
    play_view(catalogue)
  File "/home/rob/.kodi/addons/plugin.video.pluralsight/addon.py", line 281, in play_view
    token = login(catalogue)
  File "/home/rob/.kodi/addons/plugin.video.pluralsight/addon.py", line 77, in login
    login_token = response.json()["Token"]
  File "/home/rob/.kodi/addons/plugin.video.pluralsight/resources/lib/requests/models.py", line 819, in json
    return json.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/dist-packages/simplejson/__init__.py", line 488, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 389, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
  File "/usr/lib/python2.7/dist-packages/simplejson/scanner.py", line 33, in __init__
    ValueError.__init__(self, errmsg(msg, doc, pos, end=end))
TypeError: 'NoneType' object is not callable
-->End of Python script error report<--
15:12:42 T:3002636096   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.pluralsight/?cached=true&module_name=js-next-es6-m1&course_name=js-next-es6&mode=play&clip_id=0]
```

**Comment by mintsoft** [comment]
Fixed in: https://github.com/mintsoft/kodi.plugin.video.pluralsight/releases/tag/1.1.0
